### ISSUE TITLE
Uranus has copy of Neptune coefficients

### ISSUE THREAD

**Issue by thosmos** [jsauve/AASharp#1]
https://github.com/jsauve/AASharp/blob/4f977c6d0509f6bcf80346644b68b32b138e805b/Src/AASharp/AASUranus.cs#L9

**Comment by jsauve** [comment]
Oh, wow. That doesn't seem right. Feel free to issue a pull request with your changes. I don't actively maintain the lib anymore, but I'm happy to merge in any updates.

**Comment by jsauve** [comment]
@thosmos, actually, if you can get by with C++, you should use PJ Naughter's AA+ lib: http://www.naughter.com/aa.html

It appears he's been making regular updates. I haven't updated my port of his code since 2011, so mine is terribly out of date. I basically ported each of this C++ files one-by-one.

**Comment by thosmos** [comment]
I got the relevant code from https://aaplus.codeplex.com/  which appears to be exactly the same code as your project, but includes the copyright of Naughter's original C++ code.

**Comment by jsauve** [comment]
@thosmos, cool! Be mindful that Naughter has been actively updating his code over the years, and the project you've referenced is from 2009. I'm not sure if any of your calculations will be affected, but just be aware that there may be more accurate results with Naughter's code base. Maybe I'll get around to re-porting his lib to C# again someday. It's not a difficult undertaking; just very time consuming. It might be kind of neat to see how much the code is improved by new C# features.

**Comment by elendil-software** [comment]
Hi,
For your information, I recently forked this repository and began to update it to the latest version of the original C++ library. I'll do a pull request when ready

Regards

Julien

**Comment by jsauve** [comment]
@elendil-software, that's great!
