### ISSUE TITLE
Helper function to return constellation from equatorial coordinates

### ISSUE THREAD

**Issue by laheller** [jsauve/AASharp#10]
Hi @elendil-software @jsauve   !

As the title says, that function would be really useful.
There is a ready to use JavaScript application available [here](http://djm.cc/constellation.js).
Demo page is [here](http://djm.cc/constellation.html).

It would be nice to port this to our lovely AASharp.

BR,

Ladislav

**Comment by elendil-software** [comment]
Hi,

Looks interesting. I will implement it in AA#

**Comment by laheller** [comment]
@elendil-software 

In the meantime I did some research.
The theory behind is quite [common](https://en.wikipedia.org/wiki/Point_in_polygon).

Found [this](https://stackoverflow.com/questions/46144205/point-in-polygon-using-winding-number) implementation (1st answer), which works perfectly for me.
But for the above I am using [this](http://tapvizier.u-strasbg.fr/TAPVizieR/tap/sync?request=doQuery&lang=adql&query=select%20*%20from%20%22VI/49/bound_20%22%20order%20by%20recno&format=text) data. More info about constellation boundaries [here](http://cdsarc.u-strasbg.fr/viz-bin/cat/VI/49).

**Comment by elendil-software** [comment]
Ok, thank you for your research. I think I will implement it the same way than your first message and check if existing part are already in AA#

Regards

Julien

**Comment by laheller** [comment]
Yes, I also recommend to use the method in my first message, because using method/data in my second comment there are problems with constellations divided by RA = 0h (for example Andromeda, Cassiopeia).

But fortunately that first method seems to be working in all cases.

**Comment by elendil-software** [comment]
Ok, can you give me some coordinates that seems to give wrong answer ?

I've writen a first draft of c# implementation (simply converted the javascript code). Now I will write some unit test to check all is working correctly. And then I will refactor to take care of c# specificities.

**Comment by laheller** [comment]
Anything in Andromeda near DE = 32° but I think it fails for all constellations "splitted" by the RA = 0h circle.

But again: I had problems only in my own implementation where I used the [database of J2000 constellation boundaries](http://cdsarc.u-strasbg.fr/viz-bin/Cat?VI/49) and the [winding number algorithm](https://en.wikipedia.org/wiki/Point_in_polygon#Winding_number_algorithm) for polygons!!!
Reason why it did not work I can demonstrate by simply plotting two constellations Tauris and Andromeda by using their boundary data from the above DB:
![image](https://user-images.githubusercontent.com/5788998/49787416-ed806780-fd26-11e8-8866-dc3d2fa85419.png)
![image](https://user-images.githubusercontent.com/5788998/49787438-ff620a80-fd26-11e8-88fd-0569a758c67c.png)
As you can see, the Andromeda is not correctly plotted. This is not a bug of my plotting algorithm, this is the consequence of fact that coordinates in celestial coordinate system are basically points on an inner surface of a sphere, where the RA coordinate is limited to the range [0..360] (in degrees).
If you like, I can share the source code of this demo plotting application, it is very simple and you can easily reproduce the same for constellations, like Andromeda, Cassiopeia, Pisces, Sculptor, etc.

Of course when you plot/render the constellations based on this DB in a 3D scene, they will rendered correctly (I also created a demo app for it), but the algorithm will still fail.

The first method (based on the page [here](http://djm.cc/constellation.html)) should work without problems. Your implemetation (or port to C#) too.
I can help you with testing. Maybe this one will also help you to write unit tests:
The [CDS data center in Strasbourg](http://cdsportal.u-strasbg.fr/) has a very good star database connected with online services and you can easily get coordinates of any star by its name, for example:
_https://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-ox/~S?Polaris_
or other format of query:
_https://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-ox/~S?*+alf+UMi_

The above returns some basic info about Polaris in XML format, where the JRADEG and JDEDEG nodes contains its coordinates. You can use this as an input to unit tests test data.

**Comment by elendil-software** [comment]
I pushed the first version on the branch feature/constellation : https://github.com/jsauve/AASharp/tree/feature/constellations

The implementation is here https://github.com/jsauve/AASharp/blob/feature/constellations/Src/AASharp/Constellations/CoordinatesToConstellation.cs

And the unit test here : https://github.com/jsauve/AASharp/blob/feature/constellations/Test/AASharp.Tests/Constellations/CoordinatesToConstellationTest.cs

Let me know if it works for you

**Comment by elendil-software** [comment]
for the unit tests I think we could use this URL : https://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-ox/~S?*+alf+UMi and use it to generate a few points for each constellation.

I began to write a script to generate the tests

**Comment by laheller** [comment]
Hello

Today after work I'll test your implementation and will let you know the results.
And yes, that url with "star in a consetllation" type of query seems useful.
Similar way I am rendering stars from one picked constellation in the 3D scene of my planetarium application.

**Comment by elendil-software** [comment]
Hi,

I added more tests (590). Only a few part (17) doesn't pass. I have not yet checked but I think that can be stars that are part of two constellation (e.g. Alpha Andromeda)

**Comment by laheller** [comment]
Hello

Finally I had time to build the source and try your implementation/port.
Did not test all 88 constellations, but for now seems working well.
And yes, Alpha Andromeda = Delta Pegasi

If you do the web request like this:
https://cdsweb.u-strasbg.fr/cgi-bin/nph-sesame/-oxI/~S?*+alp+And
(see the difference in request: a capital "I" letter after "x")
Then it returns an XML with lot of "alias" elements, where you can see aliases for the target ;)

As I wrote, did not test everything, but I think this "issue" can be closed.
Well done my friend, a new functionality was added to this great library! 👍

**Comment by elendil-software** [comment]
I've done some modifications and improvements :

- get_name renamed in GetConstellation
- returns a Constellation object instead of a string
- throw a NotFoundException if the constellation is not found

**Comment by elendil-software** [comment]
I checked test cases that fail.

For a few cases like delta Pegasi, Beta Taurus the origin is clear, I removed the tests cases.

For the other I don't know. The stars are close to the constellation boundary, so maybe computation error somewhere.

Regards

Julien

**Comment by laheller** [comment]
@elendil-software 

Created a [demo application](https://drive.google.com/open?id=1l9ZPg30T-rGB6JdOhfbsQK-jU-8LfBPr) with 3D graphics to test your implementation.
Just unzip it and run **ConstellationDemo3D.exe**.
To navigate in 3D scene just drag the mouse (left button).
Only the constellation (boundary) under crosshair cursor shoud displayed with its name on top/right info panel. The constellation [Serpens](https://en.wikipedia.org/wiki/Serpens) is a bit tricky, it has two non-contiguous parts.

It seems that it works for all constellations, however near celestial poles the accuracy is a bit lower.

Please try my app and give feedback (here or via [email](mailto:ladislav.heller@gmail.com)).

Thank you for the effort, to port/implement this method!

Edit: Made a [video](https://drive.google.com/open?id=17fplhIX4i8NMDj3cH5a6BLLqUecCZmi1), if you don't want to directly download and try demo app.

Best Regards,

Ladislav

**Comment by elendil-software** [comment]
Looks Great !!!

I began to clean up and refactor the current implementation. I began by replacing the Precess method by the one of AASPrecession. After the modification only one test fail : epsilon sagittae.

**Comment by laheller** [comment]
Thanks!

Now I would say, that we can live with that (one failed test) and let's release new version of AASharp.
Plus maybe you can notify the author of [AA+](http://www.naughter.com/aa.html) about this feature, he can backport it to AA+.

**Comment by elendil-software** [comment]
In fact there is more failed tests. I forgot to comment one line of code.
So, I think I will make a release with the current code.

**Comment by laheller** [comment]
I think these errors are really because of precession.
How you called AASPrecession class methods? Can u provide an example?

**Comment by elendil-software** [comment]
I found where is the error. The original javascript function take the epoch in year while the AASPrecession method need it in JD. It works now.

I pushed the modification, if it work for you, I'll do the release.

**Comment by laheller** [comment]
Cool. Will let you know, once I tested.

**Comment by laheller** [comment]
@elendil-software 

OK, tested your latest changes.
Seems to be OK for most coordinates, but slightly inaccurate near the boundary lines. 
For my application this is far more, than enough.
You can also try my demo app, I uploaded the [source code](https://drive.google.com/open?id=1Uk1m3_M0fztAmFb0Z1dFzYs1yIxyd0JT).

I think a new AASharp version can be released and this "issue" can be closed.

BR,

Ladislav

**Comment by elendil-software** [comment]
Ok. I just pushed the new version on NuGet, it should be available soon (v2.0.0)

**Comment by elendil-software** [comment]
@laheller 
The CoordinatesToConstellation class has been moved in a separate project : https://www.nuget.org/packages/AASharp.Extension/
I recommand you to intall this package and the last AASharp version : 1.99.1

**Comment by laheller** [comment]
Hi again @elendil-software 

Finally I implemented my own algorithm which is **accurate** also near/on constellation boundary lines.
If you remeber, the current implementation, you added to AASharp is slightly inaccurate near/on the boundary lines.

My algorithm does not need any precession calculation, it works directly with J2000 coordinates.
For now the only problem is that it cannot deal with coordinates near celestial poles, i. e. where _Math.Abs(declination) > 83°_ (but I am working on it...) otherwise all my tests seems accurate and gives the **correct** constellation for **any** point!

As input data for constellation boundaries I am using following file from [this](http://pbarbier.com/constellations/boundaries.html) page:
_bound_in_20.txt_

The file _centers_20.txt_ on the mentioned page is also useful, it contains the weighted centers of constellations and these two files (the data) can be easily used for drawing. I suggest to add both of them to AASharp.Extension.

Are u still intereseted in improvement?

BR,

Ladislav

**Comment by elendil-software** [comment]
> Are u still intereseted in improvement?

Yes, of course

Julien

**Comment by laheller** [comment]
@elendil-software 

Quick update:
Still fighting with the same problem: When point's **DE > +85°** or **DE < -85°**, the algorithm returns **Unknown** for constellation.
I tried already at least 5 different _PointInPolygon_ algorithms found on stackoverflow, google, etc.
Btw [this](http://csharphelper.com/blog/2014/07/determine-whether-a-point-is-inside-a-polygon-in-c/) is the best one.

Now I think that the problem is not with the algorithms but with constellation data.
Anyway I will share what I did so far, maybe you can figure out, where is the problem.

**Comment by laheller** [comment]
@elendil-software 

Another update:
Got some help from a mathematician. Since we are testing location on the surface of a sphere a PointInPolygon algorithm designed for 2D polygons works only in case when we are **far** from sphere poles. It already works.
But **near** (or on) the sphere poles we must use a projection of polygon coordinates, basically take them as polar coordinates and convert to cartesian before test.
I am working on it, will let you know when finished.

**Comment by elendil-software** [comment]
Great !
As soon we have a more reliable solution I will do a new release

**Comment by laheller** [comment]
@elendil-software 

Update after some months:
Yes, it took me so long to figure out, that the constellation boundary data available at CDS has some **incorrect values**, therefore my algorithm always failed (did **not** return any constellation) for some coordinates.
I sent them a notification, you can check the details here:
http://cdsannotations.u-strasbg.fr/annotations/vizierTable/VI%252F49

Fortunately there is another source of constellation data, which seems to be correct:
http://pbarbier.com/constellations/boundaries.html

Once I finish the implementation, will let you know.

[UPDATE]
Finally it works!!!!!!!!!!
Now I am going to optimize the code and then share it with you.

BR,

Ladislav

**Comment by elendil-software** [comment]
Great !

Thank You

Regards,

Julien

**Comment by laheller** [comment]
Hi @elendil-software @jsauve 

Sorry for very very late response but if still insterested, I have the solution.
I created my own library and published it to my repo:
https://github.com/laheller/IAU.Constellations

Prebuilt demo app you can download from:
http://app.rigel.sk/win/iau.constellations.demo/publish.htm

BR,

Ladislav

**Comment by elendil-software** [comment]
Great !

Rather than integrate it in AASharp or any existing library, I suggest you publish your own NuGet package.

Regards,

Julien

**Comment by laheller** [comment]
> Great !
> 
> Rather than integrate it in AASharp or any existing library, I suggest you publish your own NuGet package.
> 
> Regards,
> 
> Julien

Hi!

Unfortunately I can't publish. At least can't publish a version visible to community, since I have no code signing certificate required for nuget publishing. :-/

**Comment by elendil-software** [comment]
Are you sure signing nuget package is required ? I don't remember having signed any package I published

**Comment by laheller** [comment]
Hi @elendil-software 

When did you that last time? :-)

For me simply the nuget.org management console says:

> Package publishing failed. This package could not be published due to the following reason(s):
> NU3018: The author primary signature found a chain building issue: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> Once you've fixed the issue with your package, you can reupload it with the same ID and version.
> 

While the package is not signed, it appears only at **Unlisted packages**:
![image](https://user-images.githubusercontent.com/5788998/78917611-69abcc00-7a8f-11ea-96ab-a5507cb1dbd3.png)

Tried to sign it using a self signed certificate, but as I expected, it did not work.

Unfortunately the nuget.org (or Microsoft ?) [changed](https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package) their policy.
So probably also you will fail with publishing, unless you do not own a proper code signing certificate.

BR,

Ladislav

**Comment by elendil-software** [comment]
> When did you that last time? :-)

It was a few month ago.

We will see when I'll try to publish the next AA# version
