### ISSUE TITLE
Link to SwiftAA?

### ISSUE THREAD

**Issue by onekiloparsec** [jsauve/AASharp#13]
Hi, 

Not an issue per-se. I just discovered your code, and since I am the author of the Objective-C(++) / Swift and Javascript versions, I thought it would be cool to link to yours. 

You may be interested to link back ? :-) 
https://github.com/onekiloparsec/SwiftAA

Best

**Comment by jsauve** [comment]
@onekiloparsec, Hello! Sorry for the late response. I can surely link to your repo. I've done so in the README.md
