### ISSUE TITLE
Implementation of the last AA+ additions

### ISSUE THREAD

**Issue by elendil-software** [jsauve/AASharp#14]
Hi @jsauve 

I implemented the last AA+ additions on the _develop_ branch. If you want to have a look before I merge it on Master and release the NuGet package.

- CAAMoonPhases2
- CAAMoonNodes2
- CAAMoonPerigeeApogee2
- CAAMoonMaxDeclinations2
- CAAEquinoxesAndSolstices2
- CAARiseTransitSet2

Regards, 

Julien

**Comment by jsauve** [comment]
Sure thing. I'll take a look now. Thanks!

**Comment by jsauve** [comment]
@elendil-software, I haven't run the unit tests in a long time, so I don't know how they were performing previously, but I'm seeing 83 failures at the moment. I'm running Mono 64 on a Mac. My environment specs:
https://gist.github.com/jsauve/84b84c953559aace3ed8f54f0a9b9fab

<img width="291" alt="Screen Shot 2020-04-06 at 5 14 51 PM" src="https://user-images.githubusercontent.com/55351/78610427-6d8ae480-782a-11ea-80e2-2594c1c2aefb.png">

**Comment by elendil-software** [comment]
It's something I already noticed in the past when I wrote the first AA# test. There is a small difference in the floating point precision between the different .NET implementations. Can you try with .NET Core ?

**Comment by jsauve** [comment]
@elendil-software, it appears that constraining the Assert.Equals(...) in the failing tests to a precision of 14 decimal places causes tests to pass. I just don't have a good sense of whether or not that's an adequate precision to rely upon for testing these algorithms. I presume so, but I don't really know. What are your thoughts?

I take back my earlier statement about Mono. I am indeed building for .NET, not Mono.

**Comment by elendil-software** [comment]
I found a few interesting topics : 
- https://stackoverflow.com/a/1395696  
- https://stackoverflow.com/a/5018263
- https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types
- https://forum.unity.com/threads/double-float-results-different-values-in-unity-and-msvs.489466/#post-3193990

> I just don't have a good sense of whether or not that's an adequate precision to rely upon for testing these algorithms. I presume so, but I don't really know. What are your thoughts?

I presume so, too. For example in a coordinate or time value a precision difference of 0.00000000000001 seems to be negligible.

**Comment by jsauve** [comment]
@elendil-software, this is interesting as well:
https://stackoverflow.com/questions/4787125/evaluate-if-two-doubles-are-equal-based-on-a-given-precision-not-within-a-certa#answer-4787767

I can spend some time updating the tests, but probably not until Sat or Sun. (It's Fri afternoon for me at the moment.)

**Comment by elendil-software** [comment]
Interesting.

Note that AA# unit test use xUnit, it's a bit different. You have to give the number of decimal you want to be the same : https://stackoverflow.com/a/57428669

**Comment by elendil-software** [comment]
@jsauve 

Did you had the time to look at those test ?
