### ISSUE TITLE
Can't open the solution

### ISSUE THREAD

**Issue by laheller** [jsauve/AASharp#5]
Hi @jsauve 

Cannot open the **AASharp.sln** solution, at least in **Visual Studio 2013**.

However, as far as I checked the source code, it looks a very good Astro library, with rich function set!

Did u consider to make it available as a **nuget package** at www.nuget.org ?

**Comment by elendil-software** [comment]
Hi,

The solution is a .NET Standard solution, it will work only with Visual Studio 2017.

Sorry @jsauve , it's my fault. I should not have deleted the old solution files, I will restore it.

**Comment by laheller** [comment]
Hello @elendil-software 

Thanks for quick respone and for restore!

And what about a nuget package of this library? Makes sense? Can u pls create it?

**Comment by elendil-software** [comment]
Restore done ! You should be able to open the solution AASharp.Net.sln with Visual Studio 2013.

A NuGet package should be available soon.

**Comment by laheller** [comment]
@elendil-software  great, thank you again!
(and I think this issue can be closed)

**Comment by laheller** [comment]
@elendil-software 
Can u pls send a link to NuGet package when ready?
Thanks!

**Comment by elendil-software** [comment]
After further investigations with @laheller we discovered that there is another problem : AA# use some C# features that are not supported by the VS2013 compiler. I'm not sure there is a way to change that.

Concerning the NuGet Package, the solution is already building a NuGet package that is targeting .Net Standard 2.0, .Net 4.0 and .Net 4.5. But it's not yet available on nuget.org feed.

**Comment by elendil-software** [comment]
A NuGet package is now available. You can install it by executing the command ``Install-Package AASharp`` in the Package Manager Console. You can also install it from the NuGet Package Manager if you prefer.

https://www.nuget.org/packages/AASharp/

**Comment by laheller** [comment]
@elendil-software 
Nuget.org now returns 2 results for aasharp:
https://www.nuget.org/packages?q=aasharp

What is the difference between them?

Otherwise I think we can close this issue.

**Comment by elendil-software** [comment]
"AASharp" v1.93 is the good one
I don't know what is the other ????

**Comment by elendil-software** [comment]
Someone forked the repository today. He has duplicated the code source in a new directory and created a new project file. There are two commit on his repository on called "Nuget package" and the other "Add framework 4.5 to nuget". I don't understand why because all was already in the solution. Only a few information were missing in the nuget properties.

**Comment by elendil-software** [comment]
I moved the VS2013 solution file in the ProjectFile directory to avoid confusion. I finally managed to compile it with VS2013. I had to add the Microsoft.Net.Compilers nuget package. It's also necessary to have MSBuild14 installed.
