### ISSUE TITLE
Is Mono Solution file still necessary ?

### ISSUE THREAD

**Issue by elendil-software** [jsauve/AASharp#6]
Hi,

I open this issue to discuss the need of the Mono solution version (AASharp.Mono.sln)

With .Net standard I'm not sure it is still necessary to keep this solution file.

Note : the solution AASharp.sln is targeting .Net Standard 2.0, .Net 4.0 and .Net 4.5. We could add .Net Standard 1.6 to support Mono 4.6

**Comment by laheller** [comment]
Maybe for Xamarin.Android developers the Mono solution could help.

**Comment by elendil-software** [comment]
Yes, but Xamarin.* is compatible with .Net Standard.
You can find a .Net Standard compatibility grid here : https://docs.microsoft.com/en-us/dotnet/standard/net-standard
And a specific solution is not necessary if MonoDevelop can load the AASharp.sln solution

**Comment by elendil-software** [comment]
I installed the last Ubuntu version and MonoDevelop. MonoDevelop can not open the .Net Standard project files, so the Mono solution is still useful.
